
[hatRandomisation]
	#For Client Config: Spawn chance when on servers that do not have Hats installed.
	#For Server Config: Spawn chance for entities which support hats.
	#Range: 0.0 ~ 1.0
	hatChance = 0.1
	#Entity chance override. Each entry should be a resource location and a chance, separated by a comma. EG: "minecraft:pig,100" will make all minecraft pigs have a 100 percent chance of having a hat.
	entityOverrideChance = []
	#The bonus to the rarity of hats spawned on bosses. EG: setting this to 1 (max) will force Bosses to only spawn with Legendary hats, should the weight be allocated correctly.
	#Range: 0.0 ~ 1.0
	bossRarityBonus = 0.2
	#Random Seed used for Hat Randomisation, rarity, spawn chance, etc. Leave blank for random generated seed.
	randSeed = "-u)Z,u;2|H&>bS(:><PV"
	#The bonus spawn chance of a boss to spawn a hat, in addition to the hatChance config.
	#Range: 0.0 ~ 1.0
	bossHatChanceBonus = 0.1
	#The weight of each of the spawn chance and rarity allocation of hats, in the order of Common, Uncommon, Rare, Epic, Legendary. Any lacking values are filled in with 0s, extra values discarded.
	rarityWeight = ["21", "13", "8", "5", "3"]
	#The Value (in HATs) of a Hat by rarity.
	rarityCost = ["10", "20", "40", "70", "110"]
	#Resource Location to disable hats on certain mobs. EG: minecraft:pig
	disabledMobs = []

#These options affect the gameplay while using the mod.
[gameplay]
	#(Not currently used, for Hat Trader update) Hats sold by the Hat Trader (planned) cost this times more than their normal value.
	#Range: 0.0 ~ 1.7976931348623157E308
	salesCostMultiplier = 10.0
	#0 = Disable Hat Selector, 1 = Only allow the fallback (entity on screen) render of the Hat Selector, 2 = Allow full hat selector GUI
	#Range: 0 ~ 2
	enabledGuiStyle = 2
	#Turning this off prevents the Hat Launcher from replacing a player's hat.
	hatLauncherReplacesPlayerHat = true
	#Do we want to send clients a toast prompt for a new hat?
	sendNewHatToastPrompt = true
	#Disabling this knocks your hat off as if you were another mob, and also removes your worn hat from your inventory. Only applies when the player is using a Hat Inventory
	hatLauncherDoesNotRemoveHatFromInventory = true
	#Allow sending of hat files between clients and servers?
	allowFileTransfer = true
	#Accessories have their own rarity. This multiplies their value by their rarity set in rarityCost
	#Range: 0.0 ~ 1.7976931348623157E308
	accessoryCostMultiplier = 1.5
	#The lifespan (in ticks) of the Hat Entity from the Hat Launcher. Be mindful this resets when a hat entity swaps out hats with another mob.
	#Range: > 0
	hatEntityLifespan = 6000
	#By default, Creative Mode players have access to all hats. Turning this on forces them to hunt for hats as if they were in Survival/Adventure
	enableCreativeModeHatHunting = false

