
[general]
	#Cracked blocks generation in The End
	end_deco = true
	#End Moss spawn rarity
	#Range: 0 ~ 16
	rarity_ogana = 5
	#End Moss spawn rarity
	#Range: 0 ~ 16
	rarity_moss = 4
	#Dragonite flower spawn rarity
	#Range: 0 ~ 16
	rarity_dragonite = 3
	#Tungsten Ore spawn rarity
	#Range: 0 ~ 16
	rarity_tungsten_ore = 3
	#Crying Obsidian spawn rarity
	#Range: 0 ~ 32
	rarity_obsidian_ore = 15
	#End Shipwreck and End Beacon generation
	end_shipwreck = true
	#Random model size | If enabled, server logs can spam with warning about enderman spawning
	enderman_tweaks = false
	#End Crypt maximum size
	#Range: 0 ~ 16
	crypt_size = 8
	#Xorcite Clusters spawn rarity
	#Range: 0 ~ 16
	rarity_xorcite_clusters = 1
	#Tungsten Ore spawn rarity
	#Range: 0 ~ 16
	rarity_tungsten_end = 2
	#Endstone Coral generation
	end_coral = true
	#End Crypt generation
	end_crypt = true

