#Number of slots in new crafted backpack
#Range: 1 ~ 63
defaultBackpackSize = 9
#Durability of Ender Backpack (-1 to make it unbreakable)
#Range: > -1
enderBackpackDurability = 128
#Number of levels required to rename backpack
#Range: > 0
backpackRenameLevelCost = 1

[pockets]

	[pockets.tiny]
		#Max count of this pocket per one backpack
		#Range: > 0
		maxCount = 9
		#Number of slots that one pocket adds to backpack
		#Range: > 1
		addSlotsCount = 1

	[pockets.medium]
		#Max count of this pocket per one backpack
		#Range: > 0
		maxCount = 3
		#Number of slots that one pocket adds to backpack
		#Range: > 1
		addSlotsCount = 3

	[pockets.large]
		#Max count of this pocket per one backpack
		#Range: > 0
		maxCount = 3
		#Number of slots that one pocket adds to backpack
		#Range: > 1
		addSlotsCount = 6

