
#Common configuration settings
[common]
	#Mutant Zombie spawn weight
	#Requires game restart
	#Range: 0 ~ 100
	mutantZombieSpawnWeight = 12
	#Mutant Skeleton spawn weight
	#Requires game restart
	#Range: 0 ~ 100
	mutantSkeletonSpawnWeight = 12
	#Mutants will only spawn in the biomes from the given mod IDs
	#Example - "minecraft", "midnight"
	#You can see a mod's ID by clicking the 'Mods' button on the main screen and clicking on the mod's name on the left
	#Requires game restart
	biomeWhitelist = [""]
	#Mutant Enderman spawn weight
	#Requires game restart
	#Range: 0 ~ 100
	mutantEndermanSpawnWeight = 12
	#Mutant Creeper spawn weight
	#Requires game restart
	#Range: 0 ~ 100
	mutantCreeperSpawnWeight = 8

